NUCLEAR LAUNCH CODES
warning: immediate genocide

diff --git a/etc/rc b/etc/rc
--- a/etc/rc
+++ b/etc/rc
@@ -1,12 +1,8 @@
 # /etc/rc - System startup script run by init before going multiuser.
 
-exec >/dev/log
-exec 2>/dev/log
-exec </dev/null
-
 umask 022
 TERM="${TERM-minix}"
-PATH=/usr/local/bin:/bin:/usr/bin:/usr/sbin:/usr/pkg/bin:/usr/pkg/sbin:/sbin
+PATH=/usr/local/bin:/bin:/usr/bin:/usr/sbin
 RC_TZ=/etc/rc.timezone
 export TERM PATH
 
@@ -18,35 +14,12 @@ usage()
 
 up()
 {
+    service=$1
+    shift
+
     # Function to dynamically start a system service
-    opt=""
-    prefix=$(expr "$1 " : '\(-\)')
-    if [ "$prefix" = "-" ];
-    then
-         opt=$1
-         shift
-    fi
-    service=$1
-    shift
-
-    service $opt up /sbin/$service "$@"
-}
-
-edit()
-{
-    # Function to dynamically edit system service settings
-    opt=""
-    prefix=$(expr "$1 " : '\(-\)')
-    if [ "$prefix" = "-" ];
-    then
-         opt=$1
-         shift
-    fi
-    service=$1
-    shift
-
-    # Assume binaries are always in /usr/sbin
-    service $opt edit /usr/sbin/$service -label $service "$@"
+    echo -n " $service"
+    service up /sbin/$service "$@"
 }
 
 while getopts 'saf' opt
@@ -69,22 +42,14 @@ esac
 
 case $action in
 start)
-    echo -n "Multiuser startup in progress ..."
+    echo ""
+    echo -n "Multiuser startup in progress ...:"
 
     # National keyboard?
     test -f /etc/keymap && loadkeys /etc/keymap
 
-    # options for fsck. default is -r, which prompts the user for repairs.
-    fsckopts="`sysenv fsckopts`"
-    if [ ! "$fsckopts" ]
-    then	fsckopts=-r
-    fi
-
-    if [ "`sysenv debug_fkeys`" != 0 ]
-    then
-        up -n is -period 5HZ
-    fi
-    echo
+    up is -period 5HZ
+    echo .
 
     # Set timezone.
     export TZ=GMT0
@@ -102,14 +67,8 @@ start)
     # /etc/fstab lists the root, tmp and usr devices.
     . /etc/fstab
 
-    # Unmount now defunct ramdisk
-    umount /dev/imgrd > /dev/null || echo "Failed to unmount boot ramdisk"
-
-    # Use MFS binary only from kernel image?
-    if [ "`sysenv bin_img`" = 1 ]
-    then
-        bin_img="-i "
-    fi
+    # Any swapspace on a device?
+    test "$swap" : '/dev/' && mount -s $swap
 
     # Are we booting from CD?
     bootcd="`/bin/sysenv bootcd`"
@@ -127,7 +86,6 @@ start)
     		echo "Setting /usr on cd is $usr"
     fi
  
-
     # Mount the /usr partition unless this is a single floppy Minix.
     if [ ! -d /usr/bin ]
     then
@@ -140,8 +98,7 @@ start)
 		echo "usr=/dev/$usr" >/tmp/usr'
 	    . /tmp/usr
 	fi
-
-	mount $bin_img $usr_roflag $usr /usr || {
+	mount $usr_roflag $usr /usr || {
 	    echo "\
 Please try to mount something else as /usr, then hit CTRL-D to continue startup.
 Mount $usr /usr failed -- Single user."
@@ -161,35 +118,19 @@ Mount $usr /usr failed -- Single user."
     if [ "$fflag" ]
     then
 	umount $usr
-	echo "fsck.mfs / - $root"
-	intr fsck.mfs $fsckopts $root
-	echo "fsck.mfs /usr - $usr"
-	intr fsck.mfs $fsckopts $usr
+	echo "fsck / - $root"
+	intr fsck -r $root
+	echo "fsck /usr - $usr"
+	intr fsck -r $usr
 	if [ ! -z "$home" ]
-	then	echo "fsck.mfs /home - $home"
-		intr fsck.mfs $fsckopts $home
+	then	echo "fsck /home - $home"
+		intr fsck -r $home
 	fi
-	mount $bin_img $usr /usr
-    fi
-
-    # Edit settings for boot system services
-    if [ "`sysenv skip_boot_config`" != 1 ]
-    then
-	edit rs
-	edit vm
-	edit pm
-	edit sched
-	edit vfs
-	edit ds
-	edit tty
-	edit memory
-	edit -p log
-	edit -c pfs
-	edit init
+	mount $usr /usr
     fi
 
     if [ ! -z "$home" ]
-    then mount $bin_img $home /home || echo "WARNING: couldn't mount $home on /home"
+    then mount $home /home || echo "WARNING: couldn't mount $home on /home"
     fi
 
     # This file is necessary for above 'shutdown -C' check.
@@ -201,6 +142,10 @@ Mount $usr /usr failed -- Single user."
 	echo "Single user."
 	intr sh
     fi
+
+    # Any swapspace on a file?
+    test -n "$swap" -a ! "$swap" : '/dev/' && mount -s $swap
+
 
     case "`printroot -r`":$bootcd in
     /dev/ram:)
@@ -223,6 +168,7 @@ esac
 # Further initialization.
 test -f /usr/etc/rc && sh /usr/etc/rc $action
 test -f /usr/local/etc/rc && sh /usr/local/etc/rc $action
+#test -f /etc/rc.rescue && sh /etc/rc.rescue $action
 
 # Any messages?
 test "$action" = start -a -f /etc/issue && cat /etc/issue
diff --git a/tools/mkboot b/tools/mkboot
--- a/tools/mkboot
+++ b/tools/mkboot
@@ -9,10 +9,10 @@ mdec=/usr/mdec	# bootstraps
 
 # Check arguments.
 case "$#:$1" in
-1:bootable | 1:hdboot | [12]:fdboot )
-	action=$1 dev=$2 size=$3
+1:bootable | 1:hdboot | [12]:fdboot | [12]:cdfdboot )
+	action=$1 dev=$2
 	;;
-*)	echo "Usage: $0 [bootable | hdboot | fdboot [device]]" >&2
+*)	echo "Usage: $0 [bootable | hdboot | cdfdboot | fdboot [device]] | cdfdboot [device]" >&2
 	exit 1
 esac
 
@@ -53,12 +53,12 @@ hdboot)
 	# Install a new image on the root device.
 	if [ ! -d $rootdir/boot/image ]
 	then
-		# /boot/image is not yet a directory!  Fix it.
+		 /boot/image is not yet a directory!  Fix it.
 		su root -c \
 		    "exec mv $rootdir/boot/image /M"
 		install -d $rootdir/boot/image
 		su root -c \
-		    "exec mv $rootdir/M $rootdir/boot/image/`uname -r`"
+		    "exec mv $rootdir/M $rootdir/boot/image/`uname -r`.`uname -v`"
 	fi
 
 	sh tell_config OS_RELEASE . OS_VERSION >/tmp/mkb.$$
@@ -108,14 +108,6 @@ hdboot)
 	# Install the new image.
 	echo "install image $root:/boot/image/$target"
 	install -o root -m 600 image $rootdir/boot/image/$target || exit
-
-	# Tell GRUB which image is newest
-	image_latest="`ls -t $rootdir/boot/image | head -n 1`"
-	if [ -f "$rootdir/boot/image/$image_latest" ]
-	then image_latest="/boot/image/$image_latest"
-	else image_latest=/boot/image_big
-	fi
-	ln -f $image_latest $rootdir/boot/image_latest
 
 	# Save the revision number.
 	test "$revision" != "$oldrev" && echo $revision >revision
@@ -169,6 +161,49 @@ fdboot)
 	edparams $dev 'main(){delay 2000;boot}; save' || exit
 	echo "Test kernel installed on $dev"
 	;;
+
+cdfdboot)
+	# cdfdboot: Make a boot floppy image to go on a CD for booting from.
+	if [ -z "$dev" ]
+	then
+		ramdisk `expr 1440 \* 1024` 2>/dev/null
+		dev=/dev/ram
+	fi
+	umount $dev 2>/dev/null
+	if mkfs -B 1024 -b 1440 -i 512 $dev || exit 1
+	then :
+	else
+		echo "mkfs of $dev failed."
+		exit 1;
+	fi
+
+	# Install /dev, /boot
+	mount $dev /mnt || exit 1
+	mkdir /mnt/dev
+	mkdir /mnt/boot
+	mkdir /mnt/boot/image
+	( cd /mnt/dev && sh /usr/src/commands/scripts/MAKEDEV.sh std )
+	cp -p image /mnt/boot/image || exit 1
+	cp -p ../boot/boot /mnt/boot/boot || exit 1
+	umount $dev || exit 1
+	installboot -d $dev ../boot/bootblock boot/boot || exit 1
+	edparams $dev '
+unset bootopts;
+unset servers;
+unset rootdev;
+unset leader;
+unset image;
+disable=inet;
+bootcd=1;
+cdproberoot=1;
+ata_id_timeout=2;
+bootbig(1, MINIX 3) { unset image; boot }
+leader() { echo \n--- Welcome to MINIX 3. This is the boot monitor. ---\n\nChoose an option from the menu or press ESC if you need to do anything special.\nOtherwise I will boot with my defaults in 10 seconds.\n\n };
+main(){trap 10000 boot; menu; };
+save' || exit
+
+	# copy image
+	dd if=$dev of=cdfdimage bs=8192 count=180
 esac
 sync
 exit 0
